### PR TITLE
Partial support for GADT used as enum types.

### PR DESCRIPTION
**Pull request by sbriais**
This provides support for such construction:

type _ event = 
| MouseOver: mouse_event event [@js "mouseover"]
| KeyDown: keyboard_event event [@js "keydown"]

by generating the function 

val event_to_js: 'a event -> Ojs.t

but not the converse function.

### CODE REVIEW

**Comment by alainfrisch** [comment]
Currently undocumented, and this might go away.

**Comment by ghost** [comment]
@alainfrisch Is this implemented? I would love to be able to use GADTs for enums. I tried it on the following example but it complains about not being able to parse the type in `t_to_js`:

``` ocaml
module Foo : sig
  type _ t =
    | Bar : int t [@js 0]
    | Baz : string t [@js "baz"]
    [@@js.enum]
  val t_to_js : 'a t -> Ojs.t
end = [%js]
```

**Comment by sbriais** [comment]
Hello,
I believe a workaround is:

module Foo : sig
  type _ t =
    | Bar : int t [@js 0]
    | Baz : string t [@js "baz"]
    [@@js.enum]
  [@@@js.stop]
  val t_to_js : 'a t -> Ojs.t
  [@@@js.start]
end = [%js]

**Comment by ghost** [comment]
@sbriais that seems to work, thanks!

**Pull request merged**
