### PR TITLE
Remove runtime funs integrated into js_of_ocaml

### PR DESCRIPTION
**Pull request by nojb**
These functions have been added to the `js_of_ocaml` runtime (see https://github.com/ocsigen/js_of_ocaml/pull/529).

### CODE REVIEW

**Comment by alainfrisch** [comment]
I guess it makes sense to include this once a public version of js_of_ocaml includes this change (and bump the opam dependency to that version).

**Comment by pveber** [comment]
I confirm these two functions have been included in `js_of_ocaml-compiler` version `3.0`.

**Comment by alainfrisch** [comment]
@sbriais already removed those primitives in https://github.com/LexiFi/gen_js_api/commit/e03387ccabbdda59d1435d1915cd461c13afed6e

But the definition for caml_ojs_new_arr is different in js_of_ocaml from what it used to be in gen_js_api:

https://github.com/ocsigen/js_of_ocaml/commit/c518e38acb7e85efcb5cd180e8e77a2a099fa98d

(apparently ignoring the last element of the array)

@sbriais  @hhugo  Was the previous version in gen_js_api buggy?  Or is this the current one (in js_of_ocaml) which is?

**Comment by hhugo** [comment]
jsoo is buggy. Will include a fix in this upcoming release.

**Comment by alainfrisch** [comment]
@hhugo Thanks for the quick confirmation!  Just to synchronize the releases, do you have an ETA for the next release of jsoo?

**Comment by hhugo** [comment]
I hope to release it this week

**Comment by alainfrisch** [comment]
Thanks @hhugo !

**Comment by hhugo** [comment]
See the RC https://github.com/ocaml/opam-repository/pull/11464

**Comment by leviroth** [comment]
It's been released! Thanks @hhugo!

**Pull request merged**
