### PR TITLE
Enable ocamlformat

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
based on #90

**Comment by hhugo** [comment]
I've rebased the feature on top of master.

**Comment by hhugo** [comment]
This is just a proposal to switch to ocamlformat.
Let me know what you think.

**Comment by nojb** [comment]
Hi @hhugo, sorry for the delay in responding.

Using `ocamlformat` would complicate the synchronization with our internal version of this code. I know about https://github.com/hhugo/merge-fmt and similar tools, but it would be an extra source of friction that we would like to avoid for the time being.

Just FYI, there are some initiatives to switch to `ocamlformat` internally, but nothing concrete yet.

**Comment by hhugo** [comment]
Noted

**Pull request closed without merging**
